version: "3.7"
services:
  redis:
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
      - /data/redis:/data
    ports:
      - "6379:6379"
    image: redis:5.0.5-alpine
    entrypoint:
      - redis-server
      - /etc/redis.conf
  mysql:
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d