version: "3.7"
services:
  redis:
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
      - ${DATA_PATH:-/data}/redis:/data
    ports:
      - "6379:6379"
    image: redis:5.0.5-alpine
    entrypoint:
      - redis-server
      - /etc/redis.conf
  mysql:
    image: mysql:5.7.27
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH:-/data}/mysql:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
  nginx:
    volumes:
      - "./nginx:/etc/nginx/"
      - "${NGINX_HTML_DIR:-./files/html}:/usr/share/nginx/html"
      - "${STATIC_DIR:-/data/caddy/static}:/usr/share/nginx/html/static"
      #- "${SSL_CERTIFICATE_LEARNING_COM:-/etc/ssl/private/1_learning.com_bundle.crt}:/etc/ssl/private/1_learning.com_bundle.crt"
      #- "${SSL_CERTIFICATE_KEY_LEARNING_COM:-/etc/ssl/private/2_learning.com.key}:/etc/ssl/private/2_learning.com.key"
      - "${NGINX_LOG_DIR:-/data/nginx/log}:/var/log/nginx"
    ports:
      - "80:80"
    environment:
      - TZ=${TIMEZONE}
    image: "nginx:1.17.2-alpine"
  rabbitmq:
    image: rabbitmq:3.7.26-management
    hostname: rabbit_node_1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${DATA_PATH:-/data}/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ${DATA_PATH:-/data}/rabbitmq/logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - TZ=${TIMEZONE}
