version: "3.7"
services:
  redis:
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
      - /data/redis:/data
    ports:
      - "6379:6379"
    image: redis:5.0.5-alpine
    entrypoint:
      - redis-server
      - /etc/redis.conf
  mysql:
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
  nginx:
    volumes:
      - "./nginx:/etc/nginx/"
      - "${NGINX_HTML_DIR:-./files/html}:/usr/share/nginx/html"
      - "${STATIC_DIR:-/data/caddy/static}:/usr/share/nginx/html/static"
      #- "${SSL_CERTIFICATE_LEARNING_COM:-/etc/ssl/private/1_learning.com_bundle.crt}:/etc/ssl/private/1_learning.com_bundle.crt"
      #- "${SSL_CERTIFICATE_KEY_LEARNING_COM:-/etc/ssl/private/2_learning.com.key}:/etc/ssl/private/2_learning.com.key"
      - "${NGINX_LOG_DIR:-/data/nginx/log}:/var/log/nginx"
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
    image: "nginx:1.17.2-alpine"